### PR TITLE
Tauri v2 (for real this time probably)

### PR DESCRIPTION
**Pull request by SpikeHD**
Porting to Tauri v2

### CODE REVIEW

**Comment by SpikeHD** [comment]
Awesome progress

image

**Comment by SpikeHD** [comment]
This is apparently due to the preinject script. Assuming I can get that working this actually doesn't seem too difficult

**Comment by SpikeHD** [comment]
Some discoveries related specifically to Windows:
* Replacing inbuilt `window` properties (e.g `fetch` or `XMLHttpRequest`) causes `STATUS_ACCESS_VIOLATION` when done too early, and I suspect Tauri v2's `initialization_script` runs earlier than v1. These were moved to a later part of the loading process.
* `tauri-plugin-http` hangs when sending requests for some reason. Does not throw an error, even if URL is something nonsensical like `__TAURI__.http.fetch('test')`.
* `load_plugins` command hangs when invoked in the frontend. It is not an infinite loop and the function does exit, so idk what's going on there.

TODO see if this happens on Linux too.

**Comment by SpikeHD** [comment]
Regarding the above ^

Tauri commands that return primitive values (string, number, bool, etc.) all work fine. Commands that return complex values, like `HashMap`s or other structs, will infinitely hang. I have not observed higher CPU usage or anything weird. The reason the HTTP module hangs is for the same reason - it returns a complex object [here](https://github.com/tauri-apps/plugins-workspace/blob/12b78a23c4a83ec014acbb5ee73a4ba53e09150d/plugins/http/src/commands.rs#L351). I have no idea where this issue resides and it's driving me insane.

**Comment by Banaanae** [comment]
Hey spike, not sure if you want bug reports with this yet, but here are my observations while running windows 11.
After installing i also got `STATUS_ACCESS_VIOLATION`, but pressing refresh fixed.
I can't send messages (this is in your server, dms dont work either)
image
(never seen that message in a public server 👀)
image
image
It seems all the api stuff is a bit whack
Last issue i found (as it's very hard to find an issue when nothing works) is with the tray icon
image
The button with the icon focuses dorion when left clicked, but does nothing when right-clicked
The button with no icon (left of dorion icon) does nothing when left clicked, but shows Open|Reload|Restart|Quit menu when right clicked)

If you need anymore testing I have both windows 11 and debian to test on

**Comment by Banaanae** [comment]
Clicking the add reaction button causes this
image
Reactions still work

**Comment by SpikeHD** [comment]
That's fine those warnings are everywhere (and happen in current Dorion too, probably), they don't seem to mean anything

**Comment by SpikeHD** [comment]
Also yes that spam of errors is due to the issues I've outlined above, this branch is very much not finished yet

**Comment by SpikeHD** [comment]
Related: https://github.com/tauri-apps/tauri/issues/10327

**Pull request merged**
